os: linux
sudo: required
dist: xenial

before_script:
    - sudo apt-get -y install texlive-latex-base texlive-xetex xutils-dev texlive-latex-extra texlive-fonts-recommended tex4ht
    - sudo apt-get -y install texlive-lang-chinese texlive-generic-recommended cjk-latex latex-cjk-chinese fonts-noto fonts-noto-cjk 
    - "./install.fandolsong.sh"
    - sudo wget https://raw.githubusercontent.com/nuxeo/presales-vmdemo/master/ImageMagick/policy.xml -O /etc/ImageMagick-6/policy.xml

script:
    - bin/makegetstart.sh zh pdf

after_script:
    - echo "===================================================================="
    - ls -lah getstart-zh/*.pdf

deploy:
  provider: releases
  api_key:
    secure: Rnw5ZUmF5OvImFrKDuIRWwAB+JJKuyeLH2WRDX1djxSG7pdMKRGph+fUYweUiAvrBCos0lTMDx7t/qVHTOuQEKClwzG2OVv2h2XyX4e67r9iiUGVqKxgPxTYbAHhEPV9OivO+sDKsYw3yv1hmq9S2R6b116C/SBPrM3A5UZpG4C0piuoyoXw7IMS+5EwpH0rLV0Czv8bTAD4osqCWVmr3velvzohHJFjStxO4lvLOlCOwVkx+1fTOJvFFBm4v31eTjDMni2cpq+Tq6uJ2XQufUchGdY+5jYFo0S4N/q+qQhTIuh38gXS04eSgKr/dYyYscWOfVakCPaq9KhyBF2AoivkYNY5DDIUrMvnYb64BHEg1JW55RE9akXGp6QKmbqukgXOKY3Op3QJJMhToqkP/MuXDvCj+YiP6dFEfzLHHjHR9Q++hBWcDgsp9Z6TPG0jLBgmLEcsDvDQIHMs2uxHZz55QibbVi33GzryHiW/veGD6nb79kz+koSfh5+Oq+qCP0qE4Re2oUAxtqHoqk1hLmc2ug4EwKHYPf1L35BACl9usjwI1YWxU9nAjmQjUw6orRQ5XfESMtsLPK7aXgFG5WX9l2UcSbvTt3Hc0YS2bCn3j1mtFiCNwUitXojdLFlB8AFnzGx9SwW7SNdyacUGUJ1X5WV9JLKYlgcJ6GUyRUc=
  file: getstart-zh/getstart-zh.pdf
  skip_cleanup: true
  on:
    tags: true
    repo: tonghuix/getstart-zh
