os: linux
 # we use the R VM because it contains LaTeX and pandoc
language: r

sudo: required
before_script:
      - uname -a 
      - lsb_release -a
      - git clone https://github.com/tonghuix/thxconfig.git
      - cd thxconfig
      - sudo mv sources.list /etc/apt/
      - sudo apt-get update
      - cd ..
      - sudo apt-get install texlive-latex-base xutils-dev texlive-latex-extra texlive-fonts-recommended tex4ht latex-cjk-chinese latex-cjk-chinese-arphic-gbsn00lp latex-cjk-chinese-arphic-gkai00mp texlive-lang-cjk
      - sudo apt-get install texlive-xetex fonts-arphic-gkai00mp fonts-arphic-ukai latex-cjk-chinese-arphic-gkai00mp fonts-arphic-gbsn00lp latex-cjk-chinese-arphic-gbsn00lp fonts-wqy-microhei fonts-wqy-zenhei
      - sudo apt-get clean
      - sudo fc-cache

script:
      - echo $`bin/makegetstart.sh zh pdf` > /dev/null

after_script:
      - echo "===================================================================="
      - mv getstart/getstart-zh.pdf .
      - ls -lah .

deploy:
  provider: releases
  api_key: "876da90ab8fdbbde6558ad7f05c0d614826bfd0c"
  file: "getstart/getstart-zh.pdf"
  skip_cleanup: true
  on:
    tags: true